config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "home#index"

  devise_for :users
  
  resources :categories do
    resources :expenses
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, :all
    can :manage, :all, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses

  validates :name, presence: true, length: { in: 2..50 }
  validates :icon, presence: true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories

  attribute :amount, default: 0

  validates :name, presence: true, length: { in: 2..50 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :expenses, dependent: :destroy

  validates :name, presence: true, length: { in: 2..50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories
  end

  # GET /categories/1 or /categories/1.json
  def show
    @expenses = @category.expenses.order(created_at: :desc)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[show edit update destroy]
  before_action :set_category
  before_action :authenticate_user!

  # GET /expenses or /expenses.json
  def index
    @expenses = @category.expenses.includes(:category)
  end

  # GET /expenses/1 or /expenses/1.json
  def show; end

  # GET /expenses/new
  def new
    @expense = Expense.new
    @selected_category = current_user.categories.find(params[:category_id])
  end

  # GET /expenses/1/edit
  def edit; end

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(expense_params)
    @expense.user_id = current_user.id
    @category.expenses << @expense

    respond_to do |format|
      if @expense.save
        format.html { redirect_to category_url(@category), notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  def set_category
    @category = Category.find(params[:category_id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to categories_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div class="d-flex p-2 bg-white border align-items-center justify-content-between" id="<%= dom_id category %>">
  <p class="display-1 text-xl"><%= category.icon %></p>
  <div>
    <h3 class="font_Caveat text-dark"><%= category.name %></h3>
    <p class="text-dark"><%= category.created_at.strftime("%d %b %Y") %></p>
  </div>
  <p class="text-dark"><%="$#{category.expenses.sum(:amount)}"%></p>
</div>

app/views/categories/_form.html.erb
<%= bootstrap_form_with(model: category, html: { class: 'p-2' }) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.select :icon,  [ ['👔'], ['👗'], ['🏠'], ['❤️'], ['✈️'], ['🐶'], ['👨‍👩‍👧‍👦'], ['🎉'], ['🛒'], ['🍕'], ['🗺️'], ['🏥'], ['🏈'], ['⛺'], ['⛱️'], ['🚲'], ['🔨'], ['📆'], ['🔒'], ['📌'], ['🕙'], ['🧹']] %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<section>
  <div class="bg-primary p-4 d-flex align-items-center justify-content-between">
    <div class="container">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <%= image_tag("menu.png") %>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to 'Categories', categories_path, class: 'nav-link text-white' %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link text-white btn secundary-text'  %>
          </li>
        </ul>
      </div>
    </div>
    <h2 class="fs-4 text-white font">CATEGORIES</h2>
  </div>

  <p style="color: green"><%= notice %></p>

  <div class="d-flex flex-column gap-2 bg-light p-2 container mt-3 mb-5">
    <% @categories.each do |category| %>
      <%= link_to category, class: 'no_txt_decoration' do %> 
        <%= render category %>
      <% end %>
   <% end %>
  </div>

  <div class="fixed-bottom bg-success btn-block p-3">
     <%= link_to "New category", new_category_path, class: 'align-self-center w-100 btn btn-outline-light text-white' %>
  </div>
</section>

app/views/categories/new.html.erb
<section>
  <div class="bg-primary p-4 d-flex align-items-center justify-content-between">
    <%= link_to image_tag("icons8-izquierda-30.png"), categories_path %>
    <h2 class="fs-4 text-white font">New category</h2>
  </div>

  <%= render "form", category: @category %>
</section>

app/views/categories/show.html.erb
<section>
  <div class="bg-primary p-4 d-flex align-items-center justify-content-between">
    <%= link_to image_tag("icons8-izquierda-30.png"), categories_path %>
    <h2 class="fs-4 text-white font">TRANSACTIONS</h2>
     <%= button_to image_tag("delete.png"), @category, method: :delete, class: 'bg-transparent border-0' %>
  </div>

  <p style="color: green"><%= notice %></p>

  <div class="bg-light  p-2" id="categories">
    <div class="d-flex p-2 bg-white border align-items-center justify-content-between" >
      <h3 class="font_Caveat"><%= "#{@category.name} #{@category.icon}" %></h3>
      <p><strong><%="$#{@category.expenses.sum(:amount)}"%></strong></p>
    </div>
  </div>

  <div class="d-flex flex-column gap-2 bg-light p-2 container mt-3 mb-5">
    <%= render @expenses %>
  </div>

  <div class="fixed-bottom bg-success btn-block p-3">
     <%= link_to "New transaction", new_category_expense_path(@category), class: 'align-self-center w-100 btn btn-outline-light text-white' %>
  </div>
  
</section>

app/views/expenses/_expense.html.erb
<div class="d-flex flex-column p-2 bg-white border" id="<%= dom_id expense %>">
  <p>
    <strong><%= "Transaction N°#{expense.id }: #{expense.name}" %></strong>
  </p>

  <p>
    <%= image_tag("time.png") %>
    <%= expense.created_at.strftime("%d %b %Y at %I:%M%P")  %>
  </p>

  <div class="d-flex justify-content-between">
    <p>Amount</p>
    <p><%= expense.amount %></p>
  </div>

</div>

app/views/expenses/_form.html.erb
<%= bootstrap_form_with(model: [category, expense], html: { class: 'p-2' }) do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.text_field :amount %>
  </div>

  <div class="form-group">
    <%= form.collection_radio_buttons(:category_id, [@selected_category], :id, :name, { item_wrapper_class: 'radio' }) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Show this expense", @expense %> |
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Expenses</h1>

<div id="expenses">
  <% @expenses.each do |expense| %>
    <%= render expense %>
    <p>
      <%= link_to "Show this expense", expense %>
    </p>
  <% end %>
</div>

<%= link_to "New expense", new_expense_path %>

app/views/expenses/new.html.erb
<section>
  <div class="bg-primary p-4 d-flex align-items-center justify-content-between">
    <%= link_to image_tag("icons8-izquierda-30.png"), category_path(@category) %>
    <h2 class="fs-4 text-white font">New transaction</h2>
  </div>

  <%= render "form", expense: @expense, category: @category %>
</section>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>

<div>
  <%= link_to "Edit this expense", edit_expense_path(@expense) %> |
  <%= link_to "Back to expenses", expenses_path %>

  <%= button_to "Destroy this expense", @expense, method: :delete %>
</div>

app/views/home/index.html.erb
<div class="p-5 d-flex flex-column align-items-center justify-content-between h_400px">
  <h1 class="font_Caveat display-2">BeFinanceFit</h1>
  <div class="d-flex flex-column w-100 gap-2">
    <%= link_to "Login", new_user_session_path, class: 'btn btn-primary' %>
    <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-light'  %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeFinanceFit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>